sudo: required
services:
  - docker

before_install:
  - docker build -t sort3d/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sort3d/react-test npm test -- --coverage

after_success:
  - docker build -t sort3d/multi-client ./client
  - docker build -t sort3d/multi-nginx ./nginx
  - docker build -t sort3d/multi-server ./server
  - docker build -t sort3d/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push sort3d/multi-client
  - docker push sort3d/multi-nginx
  - docker push sort3d/multi-server
  - docker push sort3d/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-302154339295
  bucket_path: docker-multi
  on:
    branch: master
  acccess_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY